package com.yusuffirdaus.aslirisalesdemo.upil

enum class CONFIGURATION(val CODE: Int) {
    CONNECTION_TIMEOUT(10000),
    CONNECTION_RETRY(0),
    THUMB_PIXEL(250),
    FAST_LOCATION_FREQUENCY(10000),
    LOCATION_FREQUENCY(5000),
    REQUEST_PERMISSION_LOCATION(1),
    REQUEST_CHECK_SETTINGS_GPS(2),
    UPDATE_DELAY(3000)

}
